"""
The README for this project contains some autogenerated sections (namely, command help), and this script fills those portions in.

The script requires `cp-tools-console` to be installed in the current python environment to work.
"""

import subprocess as sub
import os.path as path

IN_PATH = 'readme_fmt.md'
OUT_PATH = 'readme.md'


def get_help_message(command):
    res = sub.run([command, '--help'], stdout=sub.PIPE, stderr=sub.PIPE, text=True)
    return res.stdout.strip()


def get_file(path):
    with open(path) as f:
        return f.read().strip()


with open(IN_PATH) as f:
    data = f.read()

COMMANDS = [
    'cptools-run',
    'cptools-companion-server'
]

for command in COMMANDS:
    data = data.replace(f'$$${command} info$$$', get_help_message(command))

data = data.replace(f'$$$default configuration$$$', get_file(path.join('cptools', 'local_data', 'default_config.yml')))

with open(OUT_PATH, 'w') as f:
    f.write(data)
